export const SAVE_BOOKING_ADDRESS = 'SAVE_BOOKING_ADDRESS';
export const CHANGE_SELECTED_ADDRESS_TYPE = 'CHANGE_SELECTED_ADDRESS_TYPE';

export const AUTH_INIT = 'AUTH_INIT';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOGOUT = "AUTH_LOGOUT";